# Generated by Django 4.0.3 on 2022-04-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='jpg_image',
        ),
    ]
