# Generated by Django 4.0.3 on 2022-04-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0003_rename_text_direction_page_text_top_rotated_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocrfix',
            options={'verbose_name_plural': 'ocr fixes'},
        ),
    ]
