# Generated by Django 4.0.3 on 2022-04-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0005_box_page_original_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='page_original_image',
        ),
    ]
