# Generated by Django 4.0.3 on 2022-04-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0007_page_height_page_width_alter_page_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
