# Generated by Django 4.0.3 on 2022-04-11 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0008_box_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lsma.box'),
        ),
    ]
