# Generated by Django 4.0.3 on 2022-04-11 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0009_box_order_box_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lsma.box'),
        ),
    ]
