# Generated by Django 4.0.3 on 2022-04-12 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0011_alter_book_other_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='page',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='lsma.page'),
        ),
    ]
