# Generated by Django 4.0.3 on 2022-04-12 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0013_alter_box_options_alter_book_contributions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
    ]
