# Generated by Django 4.0.3 on 2022-04-16 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0014_alter_person_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphic',
            old_name='caption_box_checked',
            new_name='box_with_text_checked',
        ),
        migrations.RenameField(
            model_name='graphic',
            old_name='caption_height',
            new_name='height_with_text',
        ),
        migrations.RenameField(
            model_name='graphic',
            old_name='caption_left',
            new_name='left_with_text',
        ),
        migrations.RenameField(
            model_name='graphic',
            old_name='caption_top',
            new_name='top_with_text',
        ),
        migrations.RenameField(
            model_name='graphic',
            old_name='caption_width',
            new_name='width_with_text',
        ),
        migrations.RemoveField(
            model_name='page',
            name='text',
        ),
        migrations.RemoveField(
            model_name='page',
            name='text_top_rotated_to',
        ),
        migrations.RemoveField(
            model_name='table',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='table',
            name='inputs_checked',
        ),
        migrations.RemoveField(
            model_name='table',
            name='outputs',
        ),
        migrations.RemoveField(
            model_name='table',
            name='outputs_checked',
        ),
        migrations.AddField(
            model_name='book',
            name='printing_info_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printing_info_page_for', to='lsma.page'),
        ),
        migrations.AddField(
            model_name='book',
            name='printing_info_page_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='text_rotation',
            field=models.CharField(blank=True, choices=[('R', 'Clockwise'), ('L', 'Counterclockwise'), ('U', 'Upside Down')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='issue_number_kind',
            field=models.CharField(blank=True, choices=[('1', 'Arabic'), ('I', 'Roman Upper'), ('i', 'Roman Lower'), ('A', 'Letter Upper'), ('a', 'Letter Lower'), ('F', 'Ordinal Word'), ('f', 'Ordinal Number')], max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_in_series_kind',
            field=models.CharField(blank=True, choices=[('1', 'Arabic'), ('I', 'Roman Upper'), ('i', 'Roman Lower'), ('A', 'Letter Upper'), ('a', 'Letter Lower'), ('F', 'Ordinal Word'), ('f', 'Ordinal Number')], max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='volume_number_kind',
            field=models.CharField(blank=True, choices=[('1', 'Arabic'), ('I', 'Roman Upper'), ('i', 'Roman Lower'), ('A', 'Letter Upper'), ('a', 'Letter Lower'), ('F', 'Ordinal Word'), ('f', 'Ordinal Number')], max_length=1),
        ),
        migrations.AlterField(
            model_name='section',
            name='kind',
            field=models.CharField(blank=True, choices=[('CHG', 'Chapter'), ('CHA', 'Chapter Group'), ('PRE', 'Preface'), ('INT', 'Introduction'), ('DED', 'Dedication'), ('ACK', 'Acknowledgements'), ('TOC', 'Table Of Contents'), ('BIB', 'Bibliography'), ('GLO', 'Glossary'), ('APS', 'Appendices'), ('APP', 'Appendix'), ('IND', 'Index'), ('CAT', 'Publishers Catalog'), ('TAS', 'Tables'), ('ART', 'Article'), ('FIG', 'Figure'), ('PLA', 'Plates'), ('ERR', 'Errata'), ('OTH', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='section',
            name='number_kind',
            field=models.CharField(blank=True, choices=[('1', 'Arabic'), ('I', 'Roman Upper'), ('i', 'Roman Lower'), ('A', 'Letter Upper'), ('a', 'Letter Lower'), ('F', 'Ordinal Word'), ('f', 'Ordinal Number')], max_length=1),
        ),
        migrations.AlterField(
            model_name='table',
            name='number_kind',
            field=models.CharField(blank=True, choices=[('1', 'Arabic'), ('I', 'Roman Upper'), ('i', 'Roman Lower'), ('A', 'Letter Upper'), ('a', 'Letter Lower'), ('F', 'Ordinal Word'), ('f', 'Ordinal Number')], max_length=1),
        ),
    ]
