# Generated by Django 4.0.3 on 2022-04-16 16:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0015_rename_caption_box_checked_graphic_box_with_text_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='kinds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BLA', 'Blank'), ('TIT', 'Title'), ('PUB', 'Publishing Info'), ('PRI', 'Printing Info'), ('HAT', 'Half Title'), ('FCO', 'Front Cover'), ('BCO', 'Back Cover'), ('FJA', 'Front Jacket'), ('BJA', 'Back Jacket'), ('FJF', 'Front Jacket Flap'), ('BJF', 'Back Jacket Flap'), ('DEC', 'Decorative Paper'), ('FAD', 'Full Ad'), ('PAD', 'Partial Ad'), ('OTH', 'Other')], max_length=3), blank=True, null=True, size=None),
        ),
    ]
