# Generated by Django 4.0.3 on 2022-04-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0016_alter_page_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='section_kind',
            field=models.CharField(blank=True, choices=[('FIG', 'Figure'), ('PLA', 'Plate'), ('EQU', 'Equation')], max_length=3),
        ),
        migrations.AddField(
            model_name='graphic',
            name='section_kind_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graphic',
            name='section_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graphic',
            name='section_number_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graphic',
            name='section_number_kind',
            field=models.CharField(blank=True, choices=[('1', 'Arabic'), ('I', 'Roman Upper'), ('i', 'Roman Lower'), ('A', 'Letter Upper'), ('a', 'Letter Lower'), ('F', 'Ordinal Word'), ('f', 'Ordinal Number')], max_length=1),
        ),
    ]
