# Generated by Django 4.0.3 on 2022-04-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0017_graphic_section_kind_graphic_section_kind_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='kind',
            field=models.CharField(blank=True, choices=[('CHA', 'Chapter'), ('CH1', 'Chapter Group'), ('SU1', 'Subchapter'), ('PRE', 'Preface'), ('INT', 'Introduction'), ('DED', 'Dedication'), ('ACK', 'Acknowledgements'), ('TOC', 'Table Of Contents'), ('BIB', 'Bibliography'), ('GLO', 'Glossary'), ('APS', 'Appendices'), ('APP', 'Appendix'), ('IND', 'Index'), ('CAT', 'Publishers Catalog'), ('TAB', 'Table'), ('TAS', 'Tables'), ('ART', 'Article'), ('FIG', 'Figure'), ('PLA', 'Plates'), ('ERR', 'Errata'), ('OTH', 'Other')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
