# Generated by Django 4.0.3 on 2022-04-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0018_alter_section_kind_delete_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='artists_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
