# Generated by Django 4.0.3 on 2022-04-19 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lsma', '0022_graphic_title_graphic_title_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cities_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='contributions_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='copyright_page_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='copyright_years_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_published_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='edition_number_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='graphics_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='has_ligatures_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='has_vector_text_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='in_copyright_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='issue_number_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='numbers_offset_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='other_languages_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='printers_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='printing_info_page_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='printing_number_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publishers_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publishing_frequency_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='roman_numbers_offset_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='scan_color_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sections_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='series_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='subtitle_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title_page_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='topics_checked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='volume_number_checked',
        ),
        migrations.CreateModel(
            name='BookCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('kind', models.CharField(choices=[('SCA', 'Scan Color'), ('VEC', 'Vector Text'), ('TIP', 'Title Page'), ('TIT', 'Title'), ('SUB', 'Subtitle'), ('CON', 'Contributions'), ('VOL', 'Volume Number'), ('EDI', 'Edition Number'), ('ISS', 'Issue Number'), ('SER', 'Series'), ('CIT', 'Cities'), ('PUF', 'Publishing Frequency'), ('COP', 'Copyright Page'), ('DAT', 'Date Published'), ('INC', 'In Copyright'), ('COY', 'Copyright Years'), ('LIG', 'Has Ligatures'), ('PUB', 'Publishers'), ('PRN', 'Printing Number'), ('PIP', 'Printing Info Page'), ('PRI', 'Printers'), ('TOP', 'Topics'), ('SEC', 'Sections'), ('GRA', 'Graphics'), ('NUM', 'Numbers Offset'), ('RNO', 'Roman Numbers Offset'), ('LAN', 'Other Languages')], max_length=3)),
                ('checked', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='lsma.book')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
