# Generated by Django 4.0.3 on 2022-04-19 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lsma', '0024_remove_graphic_artists_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='kind',
            field=models.CharField(blank=True, choices=[('CHA', 'Chapter'), ('CHG', 'Chapter Group'), ('SUB', 'Subchapter'), ('PRE', 'Preface'), ('INT', 'Introduction'), ('DED', 'Dedication'), ('ACK', 'Acknowledgements'), ('TOC', 'Table Of Contents'), ('BIB', 'Bibliography'), ('GLO', 'Glossary'), ('APS', 'Appendices'), ('APP', 'Appendix'), ('IND', 'Index'), ('CAT', 'Publishers Catalog'), ('TAB', 'Table'), ('TAS', 'Tables'), ('ART', 'Article'), ('FIG', 'Figure'), ('PLA', 'Plates'), ('ERR', 'Errata'), ('OTH', 'Other')], max_length=3),
        ),
        migrations.CreateModel(
            name='SectionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('kind', models.CharField(choices=[('KIN', 'Kind'), ('KIB', 'Kind In Book'), ('TIT', 'Title'), ('NUM', 'Number'), ('FED', 'For Edition'), ('FPA', 'First Page'), ('LPA', 'Last Page'), ('CON', 'Contributions'), ('TOP', 'Topics')], max_length=3)),
                ('checked', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='lsma.section')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
