# Generated by Django 4.0.3 on 2022-04-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0027_check_remove_graphiccheck_checked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='book',
        ),
        migrations.AlterField(
            model_name='check',
            name='kind',
            field=models.CharField(choices=[('SCA', 'Scan Color'), ('VEC', 'Has Vector Text'), ('TIP', 'Title Page'), ('BTI', 'Book Title'), ('SUB', 'Subtitle'), ('BCO', 'Book Contributions'), ('VOL', 'Volume Number'), ('EDI', 'Edition Number'), ('ISS', 'Issue Number'), ('SER', 'Series'), ('CIT', 'Cities'), ('PUF', 'Publishing Frequency'), ('COP', 'Copyright Page'), ('DAT', 'Date Published'), ('INC', 'In Copyright'), ('COY', 'Copyright Years'), ('LIG', 'Has Ligatures'), ('PUB', 'Publishers'), ('PRN', 'Printing Number'), ('PIP', 'Printing Info Page'), ('PRI', 'Printers'), ('BTO', 'Book Topics'), ('SEC', 'Sections'), ('GRA', 'Graphics'), ('NUM', 'Numbers Offset'), ('RNO', 'Roman Numbers Offset'), ('LAN', 'Other Languages'), ('SKI', 'Section Kind'), ('KIB', 'Section Kind In Book'), ('STI', 'Section Title'), ('SNU', 'Section Number'), ('FED', 'For Edition'), ('FPA', 'First Page'), ('LPA', 'Last Page'), ('SCO', 'Section Contributions'), ('STO', 'Section Topics'), ('MED', 'Medium'), ('CON', 'Content'), ('COL', 'Print Color'), ('PAG', 'Pages'), ('ART', 'Artists'), ('CAP', 'Caption'), ('GTI', 'Graphic Title'), ('BOX', 'Box'), ('BWT', 'Box With Text'), ('GKI', 'Graphic Kind'), ('GNU', 'Graphic Number')], max_length=3),
        ),
    ]
