# Generated by Django 4.0.3 on 2022-04-20 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0029_edit_delete_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edit',
            old_name='edited_by',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='edited',
        ),
    ]
