# Generated by Django 4.0.3 on 2022-04-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0032_section_tn_ancestors_count_section_tn_ancestors_pks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcheck',
            name='new_value',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='bookcheck',
            name='old_value',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='graphiccheck',
            name='new_value',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='graphiccheck',
            name='old_value',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='sectioncheck',
            name='new_value',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='sectioncheck',
            name='old_value',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
