# Generated by Django 4.0.3 on 2022-04-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0033_bookcheck_new_value_bookcheck_old_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcheck',
            name='new_value',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='bookcheck',
            name='old_value',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='graphiccheck',
            name='new_value',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='graphiccheck',
            name='old_value',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='sectioncheck',
            name='new_value',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='sectioncheck',
            name='old_value',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
