# Generated by Django 4.0.3 on 2022-04-22 02:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0034_alter_bookcheck_new_value_alter_bookcheck_old_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='text',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='page',
            name='kinds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BLA', 'Blank'), ('TIT', 'Title'), ('PUB', 'Publishing Info'), ('PRI', 'Printing Info'), ('HAT', 'Half Title'), ('FCO', 'Front Cover'), ('BCO', 'Back Cover'), ('FJA', 'Front Jacket'), ('BJA', 'Back Jacket'), ('FJF', 'Front Jacket Flap'), ('BJF', 'Back Jacket Flap'), ('DEC', 'Decorative Paper'), ('FAD', 'Full Ad'), ('PAD', 'Partial Ad'), ('LIB', 'Library Stamp'), ('OTH', 'Other')], max_length=3), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='section',
            name='kind',
            field=models.CharField(blank=True, choices=[('FMA', 'Front Matter'), ('BOD', 'Body'), ('BMA', 'Back Matter'), ('CHA', 'Chapter'), ('CHG', 'Chapter Group'), ('SUB', 'Subchapter'), ('PRE', 'Preface'), ('INT', 'Introduction'), ('DED', 'Dedication'), ('ACK', 'Acknowledgements'), ('TOC', 'Table Of Contents'), ('BIB', 'Bibliography'), ('GLO', 'Glossary'), ('APS', 'Appendices'), ('APP', 'Appendix'), ('IND', 'Index'), ('CAT', 'Publishers Catalog'), ('TAB', 'Table'), ('TAS', 'Tables'), ('ART', 'Article'), ('FIG', 'Figure'), ('PLA', 'Plates'), ('ERR', 'Errata'), ('EPI', 'Epigraph'), ('FOR', 'Foreword'), ('LTA', 'List Of Tables'), ('LFI', 'List Of Figures'), ('LPL', 'List Of Plates'), ('LEQ', 'List Of Equations'), ('OTH', 'Other')], max_length=3),
        ),
    ]
