# Generated by Django 4.0.3 on 2022-04-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0035_alter_book_downloaded_at_alter_box_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='original_text',
            field=models.CharField(blank=True, editable=False, max_length=63),
        ),
    ]
