# Generated by Django 4.0.3 on 2022-04-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsma', '0037_alter_book_publishing_frequency_alter_graphic_medium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='content',
            field=models.CharField(blank=True, choices=[('PHO', 'Photograph'), ('MAP', 'Map'), ('CHA', 'Chart'), ('DIA', 'Diagram'), ('ILL', 'Illustration'), ('TEC', 'Technical Drawing'), ('CIR', 'Circuit Diagram'), ('DRA', 'Drawing'), ('DEC', 'Decoration'), ('EQU', 'Equation'), ('MUS', 'Music Notation'), ('TAB', 'Table')], max_length=3),
        ),
    ]
